/**
 * ResourceBlockBreakdown Component
 * Shows detailed breakdown of resources generated by each block
 */

import {
    calculateBlockResourcesPerHour,
    calculateClusterBonus,
    getBlockType,
    getLevelMultiplier,
    RESOURCE_GENERATION,
} from '@/services/resourceService';
import { Block } from '@/types';
import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

interface ResourceBlockBreakdownProps {
  blocks: Block[];
}

export default function ResourceBlockBreakdown({ blocks }: ResourceBlockBreakdownProps) {
  if (blocks.length === 0) {
    return null;
  }

  // Sort blocks by resource generation (highest first)
  const sortedBlocks = [...blocks].sort((a, b) => {
    const aRate = calculateBlockResourcesPerHour(a, blocks);
    const bRate = calculateBlockResourcesPerHour(b, blocks);
    return bRate - aRate;
  });

  const getBlockTypeIcon = (blockType: string) => {
    const icons: Record<string, string> = {
      park: '🌳',
      urban: '🏙️',
      landmark: '🗿',
      residential: '🏠',
      commercial: '🏢',
    };
    return icons[blockType] || '📍';
  };

  const getBlockTypeColor = (blockType: string) => {
    const colors: Record<string, string> = {
      park: '#10b981',
      urban: '#3b82f6',
      landmark: '#8b5cf6',
      residential: '#6b7280',
      commercial: '#f59e0b',
    };
    return colors[blockType] || '#6b7280';
  };

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Block Breakdown</Text>
      <ScrollView style={styles.scrollView} nestedScrollEnabled>
        {sortedBlocks.map((block) => {
          const blockType = getBlockType(block);
          const baseRate = RESOURCE_GENERATION.BASE_RATES[blockType] || 1;
          const levelMultiplier = getLevelMultiplier(block.level);
          const clusterBonus = calculateClusterBonus(block, blocks);
          const totalRate = calculateBlockResourcesPerHour(block, blocks);

          return (
            <View key={block.id} style={styles.blockCard}>
              {/* Header */}
              <View style={styles.blockHeader}>
                <View style={styles.blockTitleRow}>
                  <Text style={styles.blockIcon}>{getBlockTypeIcon(blockType)}</Text>
                  <View style={styles.blockInfo}>
                    <Text style={styles.blockType}>{blockType.toUpperCase()}</Text>
                    <Text style={styles.blockId} numberOfLines={1}>
                      {block.id}
                    </Text>
                  </View>
                </View>
                <View
                  style={[
                    styles.rateChip,
                    { backgroundColor: getBlockTypeColor(blockType) },
                  ]}
                >
                  <Text style={styles.rateText}>
                    {totalRate.toFixed(1)} G/hr
                  </Text>
                </View>
              </View>

              {/* Calculation Breakdown */}
              <View style={styles.calculation}>
                <View style={styles.calcRow}>
                  <Text style={styles.calcLabel}>Base Rate:</Text>
                  <Text style={styles.calcValue}>{baseRate} Gold/hr</Text>
                </View>
                <View style={styles.calcRow}>
                  <Text style={styles.calcLabel}>Level {block.level}:</Text>
                  <Text style={styles.calcValue}>×{levelMultiplier.toFixed(1)}</Text>
                </View>
                {clusterBonus > 0 && (
                  <View style={styles.calcRow}>
                    <Text style={styles.calcLabel}>Cluster Bonus:</Text>
                    <Text style={[styles.calcValue, styles.bonusText]}>
                      +{(clusterBonus * 100).toFixed(0)}%
                    </Text>
                  </View>
                )}
              </View>

              {/* Level Indicator */}
              <View style={styles.levelIndicator}>
                {[1, 2, 3].map((lvl) => (
                  <View
                    key={lvl}
                    style={[
                      styles.levelDot,
                      block.level >= lvl && styles.levelDotActive,
                    ]}
                  />
                ))}
              </View>
            </View>
          );
        })}
      </ScrollView>

      {/* Summary */}
      <View style={styles.summary}>
        <Text style={styles.summaryLabel}>Total Generation:</Text>
        <Text style={styles.summaryValue}>
          {blocks
            .reduce((sum, block) => sum + calculateBlockResourcesPerHour(block, blocks), 0)
            .toFixed(1)}{' '}
          Gold/hr
        </Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#2d2d3d',
    borderRadius: 12,
    padding: 12,
    gap: 12,
  },
  title: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 4,
  },
  scrollView: {
    maxHeight: 400,
  },
  blockCard: {
    backgroundColor: '#1e1e2e',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
    gap: 10,
  },
  blockHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  blockTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  blockIcon: {
    fontSize: 24,
  },
  blockInfo: {
    flex: 1,
  },
  blockType: {
    fontSize: 13,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 2,
  },
  blockId: {
    fontSize: 11,
    color: '#94a3b8',
  },
  rateChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  rateText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#ffffff',
  },
  calculation: {
    gap: 6,
    paddingLeft: 34,
  },
  calcRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  calcLabel: {
    fontSize: 12,
    color: '#94a3b8',
  },
  calcValue: {
    fontSize: 12,
    fontWeight: '600',
    color: '#ffffff',
  },
  bonusText: {
    color: '#10b981',
  },
  levelIndicator: {
    flexDirection: 'row',
    gap: 6,
    paddingLeft: 34,
  },
  levelDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#374151',
  },
  levelDotActive: {
    backgroundColor: '#fbbf24',
  },
  summary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#374151',
  },
  summaryLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#ffffff',
  },
  summaryValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#10b981',
  },
});
